// @ts-nocheck — template definitions use node-type strings (TASK, PERSONA, etc.)
// that pre-date the current NodeType union. Tracked in: https://github.com/YOUR_ORG/MAP/issues
import type { AgentConfig, NodeData } from './types';
import novaDemoData from './nova-demo-agent.json';
import multiagentDemoData from './multiagent-demo-agents.json';

export interface AgentTemplate {
  id: string;
  name: string;
  description: string;
  category: 'customer-service' | 'data-processing' | 'approval-workflow' | 'content-moderation' | 'orchestration';
  icon: string;
  nodes: NodeData[];
  connections: Array<{ source: string; target: string; id?: string; condition?: string }>;
  originalPrompt?: string;
}

export const TEMPLATE_CATEGORIES = [
  { id: 'customer-service', label: 'Customer Service', icon: '🎧' },
  { id: 'data-processing', label: 'Data Processing', icon: '⚙️' },
  { id: 'approval-workflow', label: 'Approval Workflows', icon: '✅' },
  { id: 'content-moderation', label: 'Content Moderation', icon: '🛡️' },
  { id: 'orchestration', label: 'Multi-Agent', icon: '🔗' },
];

export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: 'customer-support-basic',
    name: 'Basic Customer Support',
    description: 'Simple support agent with intent classification and response routing',
    category: 'customer-service',
    icon: '🎧',
    nodes: [
      {
        id: 'agent-main',
        type: 'AGENT',
        label: 'Support Agent',
        description: 'Main customer support agent',
        config: {},
        position: { x: 250, y: 50 },
      },
      {
        id: 'intent-classifier',
        type: 'TASK',
        label: 'Classify Intent',
        description: 'Determine customer intent',
        config: {},
        position: { x: 250, y: 150 },
      },
      {
        id: 'billing-rule',
        type: 'RULE',
        label: 'Billing Query',
        description: 'Route to billing',
        config: {},
        position: { x: 100, y: 250 },
      },
      {
        id: 'technical-rule',
        type: 'RULE',
        label: 'Technical Issue',
        description: 'Route to technical support',
        config: {},
        position: { x: 400, y: 250 },
      },
      {
        id: 'response-task',
        type: 'TASK',
        label: 'Generate Response',
        description: 'Create appropriate response',
        config: {},
        position: { x: 250, y: 350 },
      },
    ],
    connections: [
      { source: 'agent-main', target: 'intent-classifier' },
      { source: 'intent-classifier', target: 'billing-rule' },
      { source: 'intent-classifier', target: 'technical-rule' },
      { source: 'billing-rule', target: 'response-task' },
      { source: 'technical-rule', target: 'response-task' },
    ],
  },
  {
    id: 'approval-workflow',
    name: 'Approval Workflow',
    description: 'Multi-stage approval process with escalation',
    category: 'approval-workflow',
    icon: '✅',
    nodes: [
      {
        id: 'agent-main',
        type: 'AGENT',
        label: 'Approval Manager',
        description: 'Manages approval requests',
        config: {},
        position: { x: 250, y: 50 },
      },
      {
        id: 'validate-request',
        type: 'TASK',
        label: 'Validate Request',
        description: 'Check request completeness',
        config: {},
        position: { x: 250, y: 150 },
      },
      {
        id: 'auto-approve',
        type: 'RULE',
        label: 'Auto-Approve',
        description: 'Amount < $1000',
        config: {},
        position: { x: 100, y: 250 },
      },
      {
        id: 'manager-review',
        type: 'HANDOFF',
        label: 'Manager Review',
        description: 'Escalate to manager',
        config: {},
        position: { x: 400, y: 250 },
      },
      {
        id: 'notify-task',
        type: 'TASK',
        label: 'Send Notification',
        description: 'Notify requester',
        config: {},
        position: { x: 250, y: 350 },
      },
    ],
    connections: [
      { source: 'agent-main', target: 'validate-request' },
      { source: 'validate-request', target: 'auto-approve' },
      { source: 'validate-request', target: 'manager-review' },
      { source: 'auto-approve', target: 'notify-task' },
      { source: 'manager-review', target: 'notify-task' },
    ],
  },
  {
    id: 'content-moderator',
    name: 'Content Moderation',
    description: 'Automated content screening with safety checks',
    category: 'content-moderation',
    icon: '🛡️',
    nodes: [
      {
        id: 'agent-main',
        type: 'AGENT',
        label: 'Content Moderator',
        description: 'Reviews user-generated content',
        config: {},
        position: { x: 250, y: 50 },
      },
      {
        id: 'profanity-guard',
        type: 'GUARD',
        label: 'Profanity Filter',
        description: 'Block inappropriate language',
        config: {},
        position: { x: 250, y: 150 },
      },
      {
        id: 'spam-check',
        type: 'RULE',
        label: 'Spam Detection',
        description: 'Identify spam content',
        config: {},
        position: { x: 100, y: 250 },
      },
      {
        id: 'sentiment-check',
        type: 'TASK',
        label: 'Sentiment Analysis',
        description: 'Analyze content sentiment',
        config: {},
        position: { x: 400, y: 250 },
      },
      {
        id: 'publish-decision',
        type: 'TASK',
        label: 'Make Decision',
        description: 'Approve or reject content',
        config: {},
        position: { x: 250, y: 350 },
      },
    ],
    connections: [
      { source: 'agent-main', target: 'profanity-guard' },
      { source: 'profanity-guard', target: 'spam-check' },
      { source: 'profanity-guard', target: 'sentiment-check' },
      { source: 'spam-check', target: 'publish-decision' },
      { source: 'sentiment-check', target: 'publish-decision' },
    ],
  },
  {
    id: 'data-pipeline',
    name: 'Data Processing Pipeline',
    description: 'ETL workflow with validation and transformation',
    category: 'data-processing',
    icon: '⚙️',
    nodes: [
      {
        id: 'agent-main',
        type: 'AGENT',
        label: 'Data Pipeline',
        description: 'Processes incoming data',
        config: {},
        position: { x: 250, y: 50 },
      },
      {
        id: 'extract-task',
        type: 'TASK',
        label: 'Extract Data',
        description: 'Pull data from source',
        config: {},
        position: { x: 250, y: 150 },
      },
      {
        id: 'validate-rule',
        type: 'RULE',
        label: 'Validate Schema',
        description: 'Check data format',
        config: {},
        position: { x: 250, y: 250 },
      },
      {
        id: 'transform-task',
        type: 'TASK',
        label: 'Transform',
        description: 'Clean and transform data',
        config: {},
        position: { x: 250, y: 350 },
      },
      {
        id: 'store-memory',
        type: 'MEMORY',
        label: 'Store Results',
        description: 'Save processed data',
        config: {},
        position: { x: 250, y: 450 },
      },
    ],
    connections: [
      { source: 'agent-main', target: 'extract-task' },
      { source: 'extract-task', target: 'validate-rule' },
      { source: 'validate-rule', target: 'transform-task' },
      { source: 'transform-task', target: 'store-memory' },
    ],
  },
  {
    id: 'multi-agent-coordinator',
    name: 'Multi-Agent Coordinator',
    description: 'Orchestrates multiple specialized sub-agents',
    category: 'orchestration',
    icon: '🔗',
    nodes: [
      {
        id: 'agent-main',
        type: 'AGENT',
        label: 'Coordinator Agent',
        description: 'Main orchestration agent',
        config: {},
        position: { x: 250, y: 50 },
      },
      {
        id: 'route-task',
        type: 'TASK',
        label: 'Route Request',
        description: 'Determine which agent to use',
        config: {},
        position: { x: 250, y: 150 },
      },
      {
        id: 'agent-a',
        type: 'AGENT',
        label: 'Specialist Agent A',
        description: 'Handles domain A tasks',
        config: {},
        position: { x: 100, y: 250 },
      },
      {
        id: 'agent-b',
        type: 'AGENT',
        label: 'Specialist Agent B',
        description: 'Handles domain B tasks',
        config: {},
        position: { x: 400, y: 250 },
      },
      {
        id: 'aggregate-task',
        type: 'TASK',
        label: 'Aggregate Results',
        description: 'Combine agent outputs',
        config: {},
        position: { x: 250, y: 350 },
      },
    ],
    connections: [
      { source: 'agent-main', target: 'route-task' },
      { source: 'route-task', target: 'agent-a' },
      { source: 'route-task', target: 'agent-b' },
      { source: 'agent-a', target: 'aggregate-task' },
      { source: 'agent-b', target: 'aggregate-task' },
    ],
  },
  {
    id: 'nova-refund-arbiter',
    name: 'Nova Refund Arbiter',
    description: 'Automated Claims Adjuster for ShopCo handling refund requests with defined rules and escalation paths.',
    category: 'customer-service',
    icon: '💰',
    originalPrompt: `# Nova Refund Arbiter — System Prompt v1.2\n\n## Identity\nYou are Nova, an Automated Claims Adjuster for ShopCo. Your tone is literal and impartial. You do not express sympathy or make exceptions outside of defined rules.\n\n## Trigger\nYou activate when a user submits a refund request through the ShopCo support portal.\n\n## Step 1: Input Validation\n- If the user's message is empty or under 10 characters, respond: "Please provide more detail about your request." and terminate.\n- If the user uses aggressive or abusive language (detected via ToxicityFilter tool), respond: "This conversation has been terminated due to conduct." and end the session.\n\n## Step 2: Order Lookup\n- Call the OrderLookup tool with the provided order_id.\n- If no order_id is provided, ask the user: "Please provide your order ID to continue."\n- If the order is not found, respond: "No order found matching that ID." and terminate.\n- If the order was placed more than 90 days ago, apply Rule C (Late Claim).\n- If the order was placed more than 30 days ago but under 90 days, apply Rule B (Standard Window Check).\n- If the order was placed within 30 days, proceed to Step 3.\n\n## Step 3: Item Condition Check\n- Ask the user: "Was the item damaged, defective, or unwanted?"\n- If damaged or defective: approve full refund, log to RefundLedger tool.\n- If unwanted: check if item is in the Non-Returnable Items list (call CategoryCheck tool).\n  - If non-returnable: deny refund, respond: "This item is not eligible for return."\n  - If returnable: approve store credit only (no cash refund).\n\n## Rule B — Standard Window Check\n- Items between 30-90 days are eligible for store credit only.\n- Exception: if the item is defective AND the defect was reported within 7 days of delivery, approve full cash refund.\n- Exception: if the customer has Platinum membership (check MembershipCheck tool), approve full cash refund regardless of defect status.\n\n## Rule C — Late Claim\n- Items over 90 days are not eligible for any refund or store credit.\n- Exception: if the defect is a known manufacturer defect (call ManufacturerDefectDB tool), escalate to human supervisor.\n- Exception: if the customer has Platinum membership, apply Rule B instead.\n\n## Refund Amounts\n- Full refund: original purchase price including tax.\n- Store credit: original purchase price excluding tax.\n- Partial refund: 50% of original purchase price excluding tax (used when both damage and non-returnable status apply — see Rule D).\n\n## Rule D — Conflict Resolution\n- If an item is both damaged AND non-returnable, issue a partial refund (50%).\n- This overrides Rule C's denial if the claim is within 90 days.\n\n## Escalation\n- If the RefundLedger tool fails, escalate to human supervisor immediately.\n- If the user requests to speak to a human at any point, escalate immediately.\n- If three or more exceptions apply simultaneously, escalate to human supervisor.\n\n## Logging\n- All decisions must be logged to RefundLedger with: order_id, decision, rule_applied, timestamp.\n- Failed log attempts must be retried once before escalating.\n`,
    nodes: [
      { id: 'n1', type: 'START', label: 'Nova Refund Arbiter', description: 'Entry point for the Nova Refund Arbiter system.', config: { pfgType: 'start', column: 'center' }, position: { x: 50, y: 50 } },
      { id: 'n2', type: 'PERSONA', label: 'Agent Identity', description: "Defines the agent's role and name.", config: { logicSnippet: 'You are Nova, an Automated Claims Adjuster for ShopCo.', pfgType: 'persona', personaScope: 'agent', column: 'left' }, position: { x: -300, y: 1585 } },
      { id: 'n3', type: 'PERSONA', label: 'Response Tone', description: "Defines the agent's communication style.", config: { logicSnippet: 'Your tone is literal and impartial.', pfgType: 'persona', personaScope: 'response', column: 'right' }, position: { x: 4990, y: 50 } },
      { id: 'n4', type: 'TRIGGER', label: 'Refund Request Trigger', description: "The event that initiates the agent's workflow.", config: { logicSnippet: 'You activate when a user submits a refund request through the ShopCo support portal.', pfgType: 'trigger', column: 'right' }, position: { x: 4990, y: 284 } },
      { id: 'n5', type: 'STEP', label: 'Input Validation', description: 'First step to validate user input.', config: { pfgType: 'step', column: 'center' }, position: { x: 50, y: 250 } },
      { id: 'n6', type: 'DECISION', label: 'Message Empty or Short?', description: "Checks if the user's message is too short or empty.", config: { pfgType: 'decision', column: 'center' }, position: { x: 50, y: 450 } },
      { id: 'n7', type: 'ACTION', label: 'Request More Detail', description: 'Asks the user for more information.', config: { logicSnippet: 'respond: "Please provide more detail about your request."', pfgType: 'action', column: 'center' }, position: { x: 50, y: 650 } },
      { id: 'n8', type: 'END', label: 'Session Terminated (Input)', description: 'Session ends due to insufficient input.', config: { outcome: 'refusal', pfgType: 'end', column: 'center' }, position: { x: 50, y: 850 } },
      { id: 'n9', type: 'DECISION', label: 'Abusive Language?', description: 'Checks for aggressive or abusive language using ToxicityFilter tool.', config: { pfgType: 'decision', column: 'center' }, position: { x: 400, y: 650 } },
      { id: 'n10', type: 'TOOL', label: 'ToxicityFilter', description: 'External tool to detect abusive language.', config: { tool: 'ToxicityFilter', pfgType: 'tool', column: 'right' }, position: { x: 4990, y: 518 } },
      { id: 'n11', type: 'ACTION', label: 'Terminate Due to Conduct', description: 'Responds and ends session due to abusive language.', config: { logicSnippet: 'respond: "This conversation has been terminated due to conduct."', pfgType: 'action', column: 'center' }, position: { x: 400, y: 850 } },
      { id: 'n12', type: 'END', label: 'Session Terminated (Conduct)', description: "Session ends due to user's conduct.", config: { outcome: 'refusal', pfgType: 'end', column: 'center' }, position: { x: 400, y: 1050 } },
      { id: 'n13', type: 'STEP', label: 'Order Lookup', description: 'Step to look up order details.', config: { pfgType: 'step', column: 'center' }, position: { x: 750, y: 850 } },
      { id: 'n14', type: 'TOOL', label: 'Call OrderLookup', description: 'Invokes the OrderLookup tool with the provided order_id.', config: { tool: 'OrderLookup', pfgType: 'tool', column: 'right' }, position: { x: 4990, y: 752 } },
      { id: 'n15', type: 'INPUT', label: 'Order ID', description: "The identifier for the user's order.", config: { inputRequired: true, pfgType: 'input', column: 'left' }, position: { x: -300, y: 1715 } },
      { id: 'n16', type: 'DECISION', label: 'Order ID Provided?', description: 'Checks if an order_id was provided by the user.', config: { pfgType: 'decision', column: 'center' }, position: { x: 708, y: 1035 } },
      { id: 'n17', type: 'ACTION', label: 'Ask for Order ID', description: 'Prompts the user to provide their order ID.', config: { logicSnippet: 'ask the user: "Please provide your order ID to continue."', pfgType: 'action', column: 'center' }, position: { x: 568, y: 1261 } },
      { id: 'n18', type: 'DECISION', label: 'Order Found?', description: 'Checks if the order was successfully found.', config: { pfgType: 'decision', column: 'center' }, position: { x: 1100, y: 1250 } },
      { id: 'n19', type: 'ACTION', label: 'Order Not Found Response', description: 'Informs the user that no order was found.', config: { logicSnippet: 'respond: "No order found matching that ID."', pfgType: 'action', column: 'center' }, position: { x: 1100, y: 1450 } },
      { id: 'n20', type: 'END', label: 'Session Terminated (Order Not Found)', description: 'Session ends because the order could not be found.', config: { outcome: 'refusal', pfgType: 'end', column: 'center' }, position: { x: 1100, y: 1650 } },
      { id: 'n21', type: 'DECISION', label: 'Order Over 90 Days?', description: 'Checks if the order was placed more than 90 days ago.', config: { pfgType: 'decision', column: 'center' }, position: { x: 1450, y: 1650 } },
      { id: 'n22', type: 'DECISION', label: 'Order 30-90 Days?', description: 'Checks if the order was placed between 30 and 90 days ago.', config: { pfgType: 'decision', column: 'center' }, position: { x: 1450, y: 1850 } },
      { id: 'n23', type: 'DECISION', label: 'Order Within 30 Days?', description: 'Checks if the order was placed within 30 days.', config: { pfgType: 'decision', column: 'center' }, position: { x: 1450, y: 2050 } },
      { id: 'n24', type: 'STEP', label: 'Item Condition Check', description: 'Step to determine the condition of the item.', config: { pfgType: 'step', column: 'center' }, position: { x: 1450, y: 2250 } },
      { id: 'n25', type: 'ACTION', label: 'Ask Item Condition', description: "Asks the user about the item's condition.", config: { logicSnippet: 'Ask the user: "Was the item damaged, defective, or unwanted?"', pfgType: 'action', column: 'center' }, position: { x: 1450, y: 2450 } },
      { id: 'n26', type: 'DECISION', label: 'Damaged or Defective?', description: 'Checks if the item is damaged or defective.', config: { pfgType: 'decision', column: 'center' }, position: { x: 1450, y: 2650 } },
      { id: 'n27', type: 'RESOLUTION', label: 'Full Refund Approved', description: 'Approves a full refund for damaged or defective items.', config: { outcome: 'success', pfgType: 'resolution', column: 'center' }, position: { x: 1450, y: 2850 } },
      { id: 'n28', type: 'TASK', label: 'Log Full Refund', description: 'Logs the full refund decision to the RefundLedger tool.', config: { tool: 'RefundLedger', pfgType: 'task', column: 'center' }, position: { x: 1450, y: 3050 } },
      { id: 'n29', type: 'TOOL', label: 'RefundLedger', description: 'External tool for logging refund decisions.', config: { tool: 'RefundLedger', pfgType: 'tool', column: 'right' }, position: { x: 4990, y: 987 } },
      { id: 'n30', type: 'DECISION', label: 'Item Unwanted?', description: 'Checks if the item is unwanted and then if it is returnable.', config: { pfgType: 'decision', column: 'center' }, position: { x: 1800, y: 2650 } },
      { id: 'n31', type: 'TOOL', label: 'CategoryCheck', description: 'External tool to check if an item is in the Non-Returnable Items list.', config: { tool: 'CategoryCheck', pfgType: 'tool', column: 'right' }, position: { x: 4990, y: 1221 } },
      { id: 'n32', type: 'DECISION', label: 'Non-Returnable?', description: 'Checks if the item is non-returnable.', config: { pfgType: 'decision', column: 'center' }, position: { x: 1800, y: 2850 } },
      { id: 'n33', type: 'RESOLUTION', label: 'Refund Denied (Non-Returnable)', description: 'Denies refund for non-returnable items.', config: { outcome: 'refusal', pfgType: 'resolution', column: 'center' }, position: { x: 1800, y: 3050 } },
      { id: 'n34', type: 'RESOLUTION', label: 'Store Credit Approved', description: 'Approves store credit for returnable unwanted items.', config: { outcome: 'success', pfgType: 'resolution', column: 'center' }, position: { x: 2150, y: 3050 } },
      { id: 'n35', type: 'STEP', label: 'Rule B - Standard Window', description: 'Process for orders within the standard return window (30-90 days).', config: { pfgType: 'step', column: 'center' }, position: { x: 2500, y: 2150 } },
      { id: 'n36', type: 'RULE', label: 'Store Credit Only (30-90 Days)', description: 'Base rule for items returned within 30-90 days.', config: { ruleScope: 'scoped', pfgType: 'rule', column: 'right' }, position: { x: 4990, y: 1455 } },
      { id: 'n37', type: 'DECISION', label: 'Defective & Reported Within 7 Days?', description: 'Exception: checks for defective items reported within 7 days.', config: { pfgType: 'decision', column: 'center' }, position: { x: 2500, y: 2650 } },
      { id: 'n38', type: 'RESOLUTION', label: 'Full Cash Refund (Defect)', description: 'Approves full cash refund for qualifying defective items.', config: { outcome: 'success', pfgType: 'resolution', column: 'center' }, position: { x: 2500, y: 3050 } },
      { id: 'n39', type: 'DECISION', label: 'Platinum Member?', description: 'Exception: checks if the customer has Platinum membership.', config: { pfgType: 'decision', column: 'center' }, position: { x: 2850, y: 2850 } },
      { id: 'n40', type: 'TOOL', label: 'MembershipCheck', description: 'External tool to verify Platinum membership status.', config: { tool: 'MembershipCheck', pfgType: 'tool', column: 'right' }, position: { x: 4990, y: 1690 } },
      { id: 'n41', type: 'RESOLUTION', label: 'Full Cash Refund (Platinum)', description: 'Approves full cash refund for Platinum members.', config: { outcome: 'success', pfgType: 'resolution', column: 'center' }, position: { x: 2850, y: 3050 } },
      { id: 'n42', type: 'STEP', label: 'Rule C - Late Claim', description: 'Process for orders with late claims (over 90 days).', config: { pfgType: 'step', column: 'center' }, position: { x: 3035, y: 1905 } },
      { id: 'n43', type: 'RULE', label: 'No Refund (Over 90 Days)', description: 'Base rule for items claimed over 90 days.', config: { ruleScope: 'scoped', pfgType: 'rule', column: 'right' }, position: { x: 4990, y: 1924 } },
      { id: 'n44', type: 'DECISION', label: 'Known Manufacturer Defect?', description: 'Exception: checks for known manufacturer defects.', config: { pfgType: 'decision', column: 'center' }, position: { x: 3035, y: 2050 } },
      { id: 'n45', type: 'TOOL', label: 'ManufacturerDefectDB', description: 'External tool to check for known manufacturer defects.', config: { tool: 'ManufacturerDefectDB', pfgType: 'tool', column: 'right' }, position: { x: 4990, y: 2158 } },
      { id: 'n46', type: 'HANDOFF', label: 'Escalate to Human (Defect)', description: 'Escalates to a human supervisor for known manufacturer defects.', config: { outcome: 'escalation', pfgType: 'handoff', column: 'center' }, position: { x: 3220, y: 3050 } },
      { id: 'n47', type: 'DECISION', label: 'Platinum Member (Late Claim)?', description: 'Exception: checks if the customer has Platinum membership for late claims.', config: { pfgType: 'decision', column: 'center' }, position: { x: 3035, y: 2250 } },
      { id: 'n48', type: 'STEP', label: 'Refund Amounts', description: 'Defines the different refund amounts.', config: { pfgType: 'step', column: 'center' }, position: { x: 400, y: 50 } },
      { id: 'n49', type: 'CONFIG', label: 'Full Refund Amount', description: 'Configuration for full refund amount.', config: { logicSnippet: 'Full refund: original purchase price including tax.', pfgType: 'config', column: 'right' }, position: { x: 4990, y: 2392 } },
      { id: 'n50', type: 'CONFIG', label: 'Store Credit Amount', description: 'Configuration for store credit amount.', config: { logicSnippet: 'Store credit: original purchase price excluding tax.', pfgType: 'config', column: 'right' }, position: { x: 4990, y: 2627 } },
      { id: 'n51', type: 'CONFIG', label: 'Partial Refund Amount', description: 'Configuration for partial refund amount.', config: { logicSnippet: 'Partial refund: 50% of original purchase price excluding tax.', pfgType: 'config', column: 'right' }, position: { x: 4990, y: 2861 } },
      { id: 'n52', type: 'STEP', label: 'Rule D - Conflict Resolution', description: 'Rule for resolving conflicts between item conditions.', config: { pfgType: 'step', column: 'center' }, position: { x: 3590, y: 2650 } },
      { id: 'n53', type: 'DECISION', label: 'Damaged & Non-Returnable?', description: 'Checks if an item is both damaged and non-returnable.', config: { pfgType: 'decision', column: 'center' }, position: { x: 3590, y: 2850 } },
      { id: 'n54', type: 'RESOLUTION', label: 'Partial Refund Approved', description: 'Issues a partial refund for items that are both damaged and non-returnable.', config: { outcome: 'success', pfgType: 'resolution', column: 'center' }, position: { x: 3590, y: 3050 } },
      { id: 'n55', type: 'RULE', label: 'Rule D Overrides Rule C', description: "Rule D overrides Rule C's denial if the claim is within 90 days.", config: { ruleScope: 'scoped', pfgType: 'rule', column: 'right' }, position: { x: 4990, y: 3095 } },
      { id: 'n56', type: 'STEP', label: 'Escalation Protocol', description: 'Defines conditions under which to escalate to a human supervisor.', config: { pfgType: 'step', column: 'center' }, position: { x: 3940, y: 2250 } },
      { id: 'n57', type: 'DECISION', label: 'RefundLedger Failed?', description: 'Checks if the RefundLedger tool failed.', config: { pfgType: 'decision', column: 'center' }, position: { x: 3940, y: 2450 } },
      { id: 'n58', type: 'HANDOFF', label: 'Escalate (Tool Failure)', description: 'Escalates to human supervisor due to RefundLedger tool failure.', config: { outcome: 'escalation', pfgType: 'handoff', column: 'center' }, position: { x: 3940, y: 3050 } },
      { id: 'n59', type: 'DECISION', label: 'User Requests Human?', description: 'Checks if the user requests to speak to a human.', config: { pfgType: 'decision', column: 'center' }, position: { x: 4290, y: 2650 } },
      { id: 'n60', type: 'HANDOFF', label: 'Escalate (User Request)', description: 'Escalates to human supervisor if user requests it.', config: { outcome: 'escalation', pfgType: 'handoff', column: 'center' }, position: { x: 4290, y: 3050 } },
      { id: 'n61', type: 'DECISION', label: 'Three+ Exceptions?', description: 'Checks if three or more exceptions apply simultaneously.', config: { pfgType: 'decision', column: 'center' }, position: { x: 4640, y: 2850 } },
      { id: 'n62', type: 'HANDOFF', label: 'Escalate (Multiple Exceptions)', description: 'Escalates to human supervisor if multiple exceptions apply.', config: { outcome: 'escalation', pfgType: 'handoff', column: 'center' }, position: { x: 4640, y: 3050 } },
      { id: 'n63', type: 'STEP', label: 'Logging Requirements', description: 'Defines requirements for logging decisions.', config: { pfgType: 'step', column: 'center' }, position: { x: 750, y: 50 } },
      { id: 'n64', type: 'RULE', label: 'Log All Decisions', description: 'Mandatory logging of all decisions to RefundLedger.', config: { ruleScope: 'global', pfgType: 'rule', column: 'right' }, position: { x: 4990, y: 3330 } },
      { id: 'n65', type: 'TASK', label: 'Retry Log Attempts', description: 'Retries failed log attempts once before escalating.', config: { pfgType: 'task', column: 'center' }, position: { x: 750, y: 250 } },
      { id: 'n66', type: 'END', label: 'Refund Processed', description: 'The refund process has completed successfully.', config: { outcome: 'success', pfgType: 'end', column: 'center' }, position: { x: 3220, y: 3250 } },
    ],
    connections: [
      { id: 'e1', source: 'n1', target: 'n5', condition: 'Start Process' },
      { id: 'e2', source: 'n2', target: 'n5', condition: 'Applies to Agent' },
      { id: 'e3', source: 'n3', target: 'n1', condition: 'Applies to Agent' },
      { id: 'e4', source: 'n4', target: 'n5', condition: 'Triggers' },
      { id: 'e5', source: 'n5', target: 'n6', condition: 'Validate Input' },
      { id: 'e6', source: 'n6', target: 'n7', condition: 'Empty or < 10 chars' },
      { id: 'e7', source: 'n7', target: 'n8', condition: 'Terminate' },
      { id: 'e8', source: 'n6', target: 'n9', condition: 'Valid message' },
      { id: 'e9', source: 'n10', target: 'n9', condition: 'Provides result' },
      { id: 'e10', source: 'n9', target: 'n11', condition: 'Abusive' },
      { id: 'e11', source: 'n11', target: 'n12', condition: 'End Session' },
      { id: 'e12', source: 'n9', target: 'n13', condition: 'Not abusive' },
      { id: 'e13', source: 'n13', target: 'n16', condition: 'Lookup Order' },
      { id: 'e14', source: 'n15', target: 'n16', condition: 'Consumed by' },
      { id: 'e15', source: 'n16', target: 'n17', condition: 'No ID provided' },
      { id: 'e16', source: 'n17', target: 'n16', condition: 'User provides ID' },
      { id: 'e17', source: 'n16', target: 'n18', condition: 'ID provided' },
      { id: 'e18', source: 'n14', target: 'n18', condition: 'Provides result' },
      { id: 'e19', source: 'n18', target: 'n19', condition: 'Order not found' },
      { id: 'e20', source: 'n19', target: 'n20', condition: 'Terminate' },
      { id: 'e21', source: 'n18', target: 'n21', condition: 'Order found' },
      { id: 'e22', source: 'n21', target: 'n42', condition: 'Over 90 days' },
      { id: 'e23', source: 'n21', target: 'n22', condition: 'Not over 90 days' },
      { id: 'e24', source: 'n22', target: 'n35', condition: '30-90 days' },
      { id: 'e25', source: 'n22', target: 'n23', condition: 'Not 30-90 days' },
      { id: 'e26', source: 'n23', target: 'n24', condition: 'Within 30 days' },
      { id: 'e27', source: 'n24', target: 'n25', condition: 'Check Condition' },
      { id: 'e28', source: 'n25', target: 'n26', condition: 'User provides condition' },
      { id: 'e29', source: 'n26', target: 'n27', condition: 'Damaged or defective' },
      { id: 'e30', source: 'n27', target: 'n28', condition: 'Log Refund' },
      { id: 'e31', source: 'n28', target: 'n66', condition: 'Refund Logged' },
      { id: 'e32', source: 'n29', target: 'n28', condition: 'Used by' },
      { id: 'e33', source: 'n26', target: 'n30', condition: 'Unwanted' },
      { id: 'e34', source: 'n31', target: 'n32', condition: 'Provides result' },
      { id: 'e35', source: 'n30', target: 'n32', condition: 'Check Category' },
      { id: 'e36', source: 'n32', target: 'n33', condition: 'Non-returnable' },
      { id: 'e37', source: 'n33', target: 'n66', condition: 'Refund Denied' },
      { id: 'e38', source: 'n32', target: 'n34', condition: 'Returnable' },
      { id: 'e39', source: 'n34', target: 'n66', condition: 'Store Credit Issued' },
      { id: 'e40', source: 'n35', target: 'n37', condition: 'Check Exceptions' },
      { id: 'e41', source: 'n36', target: 'n35', condition: 'Governs' },
      { id: 'e42', source: 'n37', target: 'n38', condition: 'Defective & reported within 7 days' },
      { id: 'e43', source: 'n38', target: 'n66', condition: 'Refund Approved' },
      { id: 'e44', source: 'n37', target: 'n39', condition: 'Not defective or late report' },
      { id: 'e45', source: 'n40', target: 'n39', condition: 'Provides result' },
      { id: 'e46', source: 'n39', target: 'n41', condition: 'Platinum member' },
      { id: 'e47', source: 'n41', target: 'n66', condition: 'Refund Approved' },
      { id: 'e48', source: 'n39', target: 'n66', condition: 'Not Platinum member' },
      { id: 'e49', source: 'n42', target: 'n44', condition: 'Check Exceptions' },
      { id: 'e50', source: 'n43', target: 'n42', condition: 'Governs' },
      { id: 'e51', source: 'n45', target: 'n44', condition: 'Provides result' },
      { id: 'e52', source: 'n44', target: 'n46', condition: 'Known manufacturer defect' },
      { id: 'e53', source: 'n46', target: 'n66', condition: 'Escalated' },
      { id: 'e54', source: 'n44', target: 'n47', condition: 'No manufacturer defect' },
      { id: 'e55', source: 'n47', target: 'n35', condition: 'Platinum member' },
      { id: 'e56', source: 'n47', target: 'n66', condition: 'Not Platinum member' },
      { id: 'e57', source: 'n52', target: 'n53', condition: 'Resolve Conflicts' },
      { id: 'e58', source: 'n53', target: 'n54', condition: 'Damaged & non-returnable' },
      { id: 'e59', source: 'n54', target: 'n66', condition: 'Partial Refund Issued' },
      { id: 'e60', source: 'n55', target: 'n53', condition: 'Governs' },
      { id: 'e61', source: 'n56', target: 'n57', condition: 'Check Escalation Conditions' },
      { id: 'e62', source: 'n57', target: 'n58', condition: 'RefundLedger fails' },
      { id: 'e63', source: 'n58', target: 'n66', condition: 'Escalated' },
      { id: 'e64', source: 'n57', target: 'n59', condition: 'RefundLedger succeeds' },
      { id: 'e65', source: 'n59', target: 'n60', condition: 'User requests human' },
      { id: 'e66', source: 'n60', target: 'n66', condition: 'Escalated' },
      { id: 'e67', source: 'n59', target: 'n61', condition: 'User does not request human' },
      { id: 'e68', source: 'n61', target: 'n62', condition: 'Three or more exceptions' },
      { id: 'e69', source: 'n62', target: 'n66', condition: 'Escalated' },
      { id: 'e70', source: 'n61', target: 'n66', condition: 'Fewer than three exceptions' },
      { id: 'e71', source: 'n63', target: 'n65', condition: 'Process Logging' },
      { id: 'e72', source: 'n64', target: 'n1', condition: 'Applies to Agent' },
    ],
  },
];

// Static demo agent — always shown in the sidebar, never stored in localStorage
// Uses the full node data from nova-demo-agent.json so all logicSnippet / sourceSection fields are intact
export const DEMO_AGENT: AgentConfig = {
  ...(novaDemoData as unknown as AgentConfig),
  id: 'demo-nova-refund-arbiter',
};

// Static multiagent demo family — always shown in the sidebar, never stored in localStorage
export const DEMO_AGENTS: AgentConfig[] = multiagentDemoData as unknown as AgentConfig[];

export function createAgentFromTemplate(template: AgentTemplate): AgentConfig {
  const ts = Date.now();
  return {
    id: `agent-${ts}`,
    name: template.name,
    description: template.description,
    originalPrompt: template.originalPrompt,
    nodes: template.nodes.map(node => ({ ...node, id: `${node.id}-${ts}` })),
    connections: template.connections.map(conn => ({
      ...conn,
      source: `${conn.source}-${ts}`,
      target: `${conn.target}-${ts}`,
    })),
    version: '1.0.0',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
